language: cpp
compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
        - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
        - cmake
        - cmake-data

script:
    - $CXX --version 
    - mkdir build 
    - cd build
    - cmake .. && make
