sudo: false
language: cpp
notifications:
    email: false
os:
    - linux
    - osx
compiler:
    - gcc
    - clang
before_install:
    - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm38 && brew link --force --overwrite llvm38; fi
    - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew unlink cmake && brew install cmake && brew link --force --overwrite cmake; fi
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - gcc-4.8
        - g++-4.8
        - clang
        - cmake
        - cmake-data

script:
    - $CXX --version 
    - mkdir build 
    - cd build
    - cmake .. && make
