sudo: false
language: cpp
os:
    - linux
    - osx
compiler:
    - gcc
    - clang
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
        - gcc-4.8
        - g++-4.8
        - clang
        - cmake
        - cmake-data

script:
    - $CXX --version 
    - mkdir build 
    - cd build
    - cmake .. && make
